PREFIX adr: <http://147.87.7.145:7200/repositories/SwissKnowledgeGraphforthePerformingArts/> 
PREFIX prov: <http://www.w3.org/ns/prov#> 
PREFIX schema: <http://schema.org/> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
insert data { graph <graphUri> { <graphUri>  a prov:Entity ; 
      schema:name "<name>"  ; 
      schema:url "<url>" ; 
      prov:generatedAtTime "<generatedAtTime>"^^xsd:dateTime ;  
      prov:wasAttributedTo <wasAttributedToToolUri> ;     
      prov:wasAttributedTo <wasAttributedToOrgUri> ; 
      prov:wasDerivedFrom <wasDerivedFromUri> ;
      <http://creativecommons.org/ns#license> <https://creativecommons.org/publicdomain/mark/1.0> .
  } 
}
